// <auto-generated />
namespace Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedPizzaPriceForOrderDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPizzaPriceForOrderDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202103201058538_addedPizzaPriceForOrderDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
